name: flutter_gokwik
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  upi_pay:
    path: ./upi_pay
  argon_buttons_flutter: ^1.0.6
  eventify: ^0.1.4
  flutter_animated_dialog: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_spinkit: ^4.1.2
  http: ^0.12.1
  otp_text_field: ^1.0.2
  progress_dialog: ^1.2.4
  sms_otp_auto_verify: ^1.2.2
  timer_button: ^1.0.1
  flutter_countdown_timer: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_gokwik
        pluginClass: FlutterGokwikPlugin
      ios:
        pluginClass: FlutterGokwikPlugin

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
